env: play
enable_bot: True
output_dir: trajs

policy: eff_ctraj_1x
ckpt_path: ${oc.env:JARVISBASE_PRETRAINED}/2-3000.ckpt

on_switch_bot: 
  - plan_on_after_bot_step 
on_after_bot_step: 
  - plan_on_after_bot_step